name: Decentralized Video Platform - Continuous Deployment

# When Workflow is triggered
on:
  push:
    branches: [ main ]

# Jobs to carry out
jobs:
  deploy:
    # Operating System to run Jobs on
    runs-on: ubuntu-latest
    steps:
      # Get code from Repository
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16
      # Run npm install and build on Code
      - run: npm install
      - run: npm run build
      # Deploy to Netlify using Secrets
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          BSC_TESTNET_NODE: ${{ secrets.BSC_TESTNET_NODE }}
          ROPSTEN_TESTNET_NODE: ${{ secrets.ROPSTEN_TESTNET_NODE }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'