name: Decentralized Video Platform - Continuous Deployment

# When Workflow is triggered
on:
  push:
    branches: [ main ]

# Jobs to carry out
jobs:
  deploy:
    # Operating System to run Jobs on
    runs-on: ubuntu-latest
    steps:
      # Get code from Repository
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16
      # Run npm install (clean install) and build on Code
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: false
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BSC_TESTNET_NODE: ${{ secrets.BSC_TESTNET_NODE }}
          ROPSTEN_TESTNET_NODE: ${{ secrets.ROPSTEN_TESTNET_NODE }}
      # Deploy to Netlify using Secrets
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./build"
          deploy-message: "Deployed from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
